export const colors = {
  primary: "#9FC645",
  secondary: "#F7CA0D",
  white: "#fff",
};

export const PRODUCT_COLORS = [
  { name: "Rojo", value: "#FF0000" },
  { name: "Verde", value: "#00FF00" },
  { name: "Azul", value: "#0000FF" },
  { name: "Negro", value: "#000000" },
  { name: "Blanco", value: "#FFFFFF" },
  { name: "Amarillo", value: "#FFFF00" },
  { name: "Naranja", value: "#FFA500" },
  { name: "Rosa", value: "#FFC0CB" },
  { name: "Morado", value: "#800080" },
  { name: "Marrón", value: "#8B4513" },
  { name: "Gris", value: "#808080" },
  { name: "Beige", value: "#F5F5DC" },
  { name: "Celeste", value: "#87CEEB" },
  { name: "Turquesa", value: "#40E0D0" },
  { name: "Dorado", value: "#FFD700" },
  { name: "Plateado", value: "#C0C0C0" },
  { name: "Violeta", value: "#EE82EE" },
  { name: "Verde oscuro", value: "#006400" },
  { name: "Azul marino", value: "#000080" },
  { name: "Coral", value: "#FF7F50" },
  { name: "Lila", value: "#C8A2C8" },
  { name: "Mostaza", value: "#FFDB58" },
  { name: "Oliva", value: "#808000" },
  { name: "Cobre", value: "#B87333" },
  { name: "Champán", value: "#F7E7CE" },
  { name: "Caqui", value: "#F0E68C" },
  { name: "Granate", value: "#800000" },
  { name: "Azul claro", value: "#ADD8E6" },
  { name: "Verde lima", value: "#BFFF00" },
  { name: "Lavanda", value: "#E6E6FA" },
  { name: "Salmón", value: "#FA8072" },
  { name: "Aguamarina", value: "#7FFFD4" },
  { name: "Marfil", value: "#FFFFF0" },
  { name: "Perla", value: "#EAE0C8" },
  { name: "Azul petróleo", value: "#008080" },
  { name: "Verde menta", value: "#98FF98" },
  { name: "Terracota", value: "#E2725B" },
  { name: "Azul cielo", value: "#87CEFA" },
  { name: "Chocolate", value: "#D2691E" },
  { name: "Arena", value: "#C2B280" },
  { name: "Azul acero", value: "#4682B4" },
  { name: "Verde esmeralda", value: "#50C878" },
  { name: "Magenta", value: "#FF00FF" },
  { name: "Cian", value: "#00FFFF" },
  { name: "Azul zafiro", value: "#0F52BA" },
  { name: "Verde pistacho", value: "#93C572" },
  { name: "Rojo vino", value: "#722F37" },
  { name: "Azul turquesa", value: "#30D5C8" },
  { name: "Verde jade", value: "#00A86B" },
  { name: "Rojo cereza", value: "#DE3163" },
  { name: "Azul eléctrico", value: "#7DF9FF" },
  { name: "Verde bosque", value: "#228B22" },
  { name: "Azul cobalto", value: "#0047AB" },
  { name: "Verde oliva oscuro", value: "#556B2F" },
  { name: "Rojo ladrillo", value: "#B22222" },
  { name: "Azul real", value: "#4169E1" },
  { name: "Verde musgo", value: "#8A9A5B" },
  { name: "Rojo coral", value: "#FF4040" },
  { name: "Azul hielo", value: "#B2FFFF" },
  { name: "Verde manzana", value: "#8DB600" },
  { name: "Rojo tomate", value: "#FF6347" },
  { name: "Azul pastel", value: "#A7C7E7" },
  { name: "Verde pasto", value: "#7CFC00" },
  { name: "Rojo rubí", value: "#E0115F" },
  { name: "Azul denim", value: "#1560BD" },
  { name: "Verde aguacate", value: "#568203" },
  { name: "Rojo anaranjado", value: "#FF5349" },
  { name: "Azul índigo", value: "#4B0082" },
  { name: "Verde perla", value: "#D1E231" },
  { name: "Rojo fresa", value: "#FC5A8D" },
  { name: "Azul ultramar", value: "#3F00FF" },
  { name: "Verde botella", value: "#006A4E" },
  { name: "Rojo escarlata", value: "#FF2400" },
  { name: "Azul prusia", value: "#003153" },
  { name: "Verde militar", value: "#4B5320" },
  { name: "Rojo carmesí", value: "#DC143C" },
  { name: "Azul celeste", value: "#B0E0E6" },
  { name: "Verde mar", value: "#2E8B57" },
  { name: "Rojo óxido", value: "#B7410E" },
  { name: "Azul grisáceo", value: "#6699CC" },
  { name: "Verde lima claro", value: "#D0F0C0" },
  { name: "Rojo pastel", value: "#FF6961" },
  { name: "Azul lavanda", value: "#E3E4FA" },
  { name: "Verde menta claro", value: "#AAF0D1" },
  { name: "Rojo pálido", value: "#FFD1DC" },
  { name: "Azul noche", value: "#003366" },
  { name: "Verde pálido", value: "#98FB98" },
  { name: "Rojo oscuro", value: "#8B0000" },
  { name: "Azul profundo", value: "#191970" },
  { name: "Verde esmeralda claro", value: "#A7FC00" },
];
