export const DepartmentNames = {
  AUTOMOTRIZ: "Automotriz",
  BEBES: "Niños y bebés",
  DEPORTES: "Deportes y Outdoor",
  ELECTROHOGAR: "Electrohogar",
  ENTRETENCION: "Entretención",
  HERRAMIENTAS: "Herramientas y Maquinaria",
  HOGAR: "Hogar y Decoración",
  INSTRUMENTOSMUSICALES: "Instrumentos Musicales",
  JARDIN: "Jardín y Terraza",
  MASCOTAS: "Mascotas",
  ROPA: "Ropa, Calzado y Accesorios",
  SERVICIOS: "Servicios",
  TECNOLOGIA: "Tecnología",
};
