services:
  ekoru-web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: ekoru-web
    ports:
      - "8000:8000"
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
