services:
  app_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    container_name: app_prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.prod
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
