services:
  ekoru-web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: ekoru-web
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
